---
language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
addons:
  code_climate:
      repo_token: efd452491e0acf7af957b09664e626dd113932a4207a68ed8df7dce167ec212
after_success:
  - yarn eslint src
  - yarn test -- --coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
